#! /bin/bash
mkdir -p /root/bot/1
git clone https://github.com/Xtao-Labs/PagerMaid-Modify /root/bot/pagermaid
cp -r /root/bot/pagermaid /root/bot/1

tee /root/bot/1/docker-compose.yml << 'EOF'
version: "2.0"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    volumes:
      - /root/bot/1/pagermaid:/pagermaid/workdir
    environment:
      - RUN_AS_ROOT=true
EOF

cd /root/bot/1/
docker-compose up -d
docker exec -it 1-pagermaid-1 bash utils/docker-config.sh
