#! /bin/bash
mkdir -p /root/bot/2
cd /root/bot/2
git clone https://github.com/Xtao-Labs/PagerMaid-Modify /root/bot/2/PagerMaid-Modify
tee /roo/bot/2/PagerMaid-Modify/docker-compose.yml << 'EOF'
version: "2.0"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    container_name: pagermaid2
    hostname: pagermaid
    #ports:
      #- "3333:3333"
    volumes:
      - ./:/pagermaid/workdir
    environment:
      - RUN_AS_ROOT=true
      - PUID=917
      - PGID=917
EOF
cd /root/bot/2/PagerMaid-Modify
docker-compose up -d
docker exec -it pagermaid2 bash utils/docker-config.sh
