#! /bin/bash
mkdir -p /root/bot/2
wget https://raw.githubusercontent.com/mslxi/bot/main/docker-compsoe.yml -O /root/bot/2/docker-compose.yml
cd /root/bot/2/
docker-compose up -d
docker exec -it 1-pagermaid-1 bash utils/docker-config.sh
