#! /bin/bash
mkdir -p /root/bot/3
cp -r /root/bot/pagermaid /root/bot/3

tee /root/bot/3/docker-compose.yml << 'EOF'
version: "2.0"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    volumes:
      - /root/bot/3/pagermaid:/pagermaid/workdir
    environment:
      - RUN_AS_ROOT=true
EOF

cd /root/bot/3
docker-compose up -d
docker exec -it 3-pagermaid-3 bash utils/docker-config.sh
