#! /bin/bash
mkdir -p /root/bot/4
cp -r /root/bot/pagermaid /root/bot/4

tee /root/bot/4/docker-compose.yml << 'EOF'
version: "2.0"
services:
  pagermaid:
    image: mrwangzhe/pagermaid_modify
    restart: always
    volumes:
      - /root/bot/4/pagermaid:/pagermaid/workdir
    environment:
      - RUN_AS_ROOT=true
EOF

cd /root/bot/4
docker-compose up -d
docker exec -it 4-pagermaid-4 bash utils/docker-config.sh
